apiVersion: v1
kind: ReplicationController
metadata:
  name: database
  labels:
    name: database
spec:
  replicas: 1
  selector:
    name: database
  template:
    metadata:
      labels:
        name: database
    spec:
      containers:
        - name: postgres
          image: {docker_hub_account}/postgresql:9.5
          env:
            - name: POSTGRES_DB
              value: app_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: app_db_user
            - name: POSTGRES_PASSWORD
              value: app_db_pw
          ports:
            - containerPort: 5432
